apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-image
          image: v1commerce_api
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
